name: Check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        shell: "bash"
        working-directory: ./
        run: pnpm run build

      - name: Lint
        shell: "bash"
        working-directory: ./
        run: pnpm run lint

      - name: Test
        shell: "bash"
        working-directory: ./
        run: pnpm run test
